### ISSUE TITLE
Segfault in vitree_rebuild when opening empty file

### ISSUE THREAD

**Issue by The-Compiler** [drbig/snb#9]
When running `snb emptyfile.md` I get a segfault here:

```
#0  vitree_rebuild (s=s@entry=0x555555843350, e=e@entry=0x0) at src/ui.c:1046
#1  0x0000555555559c7c in ui_set_root (e=0x0) at src/ui.c:1752
#2  0x0000555555555a13 in main (argc=<optimized out>, argv=<optimized out>) at src/snb.c:136
```

**Comment by drbig** [comment]
Should be fixed now.

Thanks for reporting!
